{{ $annotations := dict
                  "argocd.argoproj.io/hook" "PostSync,PostDelete"
                  "helm.sh/hook" "post-install,post-delete"
                  "helm.sh/hook-delete-policy" "hook-succeeded"
                    | toYaml | nindent 4 }}
{{ $hookName := "external-monitoring-restart-prometheus-hook"}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $hookName }}
  annotations: {{ $annotations }}
spec:
  template:
    metadata:
      name: {{ $hookName }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ $hookName }}
      containers:
        - name: restart-prometheus
          image: {{ .Values.images.kubectl }}
          command: [ kubectl, rollout, restart,
                     "{{ .Values.prometheus.kind }}",
                     --selector={{ .Values.prometheus.selector }},
                     -n, {{ .Release.Namespace }} ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $hookName }}
  annotations: {{ $annotations }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $hookName }}
  annotations: {{ $annotations }}
rules:
  - apiGroups: [ apps ]
    verbs: [ list, patch ]
    resources: [ {{ .Values.prometheus.kind }}s ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $hookName }}
  annotations: {{ $annotations }}
subjects:
  - kind: ServiceAccount
    name: {{ $hookName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $hookName }}
---